name: Use API Key

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use API Key in Environment Variable
        env:
          API_KEY: ${{ secrets.CRYPTO_API_KEY }}

      - name: Check to see if key is saved
        run: |
          echo "API_KEY is set"
          # The API_KEY environment variable is set, but it will not print the actual value to avoid security risks.
          echo "The API Key has been set in the environment variable (without displaying it)."
