name: Use API Key

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.CRYPTO_API_KEY }}

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
